apiVersion: apps/v1
kind: Deployment
metadata:
   name: db-deployment
   labels:
      app: myapp
      type: database

spec:
   template:
      metadata:
         name: db-pod
         labels:
            app: myapp
            type: mongo-db

      spec:
         containers:
            - name: mongodb
              image: mongo:latest
              ports:
                - containerPort: 27017
   replicas: 1
   selector:
      matchLabels:
         app: myapp
         type: mongo-db

---
apiVersion: v1
kind: Service
metadata:
   name: mongo
spec:
   type: ClusterIP
   ports:
     - targetPort: 27017
       port: 80
   selector:
      app: myapp
      type: mongo-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: my-app-deployment

spec:
   template:
      metadata:
         name: pod-deployment
         labels:
            app: my-app
            type: rest-api

      spec:
         containers:
            - name: backend-api
              image: shadidevsecops/simple-api:2.0
              ports:
              - containerPort: 10253
   replicas: 1
   selector:
      matchLabels:
         app: my-app
         type: rest-api
---
apiVersion: v1
kind: Service
metadata:
   name: api-service
spec:
   type: NodePort
   ports:
     - targetPort: 10253
       port: 80
       nodePort: 30005
   selector:
      app: myapp
      type: rest-api
