apiVersion: apps/v1
kind: Deployment
metadata:
   name: my-app-deployment

spec:
   template:
      metadata:
         name: first-pod-dec-deployment
         labels:
            app: my-app
            type: rest-api

      spec:
         containers:
            - name: simple-api
              image: shadidevsecops/simple-api:2.0
   replicas: 5
   selector:
      matchLabels:
         app: my-app
         type: rest-api
